info:
  description: test app
server:
  port: 8080

spring:
  application:
    name: product
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      hibernate.ddl-auto: update
    # Enabling H2 Console
    h2.console.enabled: true
  main:
    allow-bean-definition-overriding: true